### ISSUE TITLE
cannot build on Mac M2 using xcode toolchain

### ISSUE THREAD

**Issue by alex-tee** [lsp-plugins/lsp-dsp-lib#21]
I downloaded the latest release tarball, then I did:
```
make config PREFIX=/opt/lsp-dsp-lib
```

Then
```
make PREFIX=/opt/lsp-dsp-lib
```

and i got the following error (sorry for the screenshot, I can't copy paste from this VM):

![image](https://github.com/user-attachments/assets/1ee45ae4-ccb8-4341-bd0f-57f9b3edf401)

System info:
- Mac mini 2023
- Apple M2 chip
- Sonoma 14.4
- Clang version `arm64-apple-darwin23.4.0`

**Comment by sadko4u** [comment]
Hello! What does `uname -m` say?
It seems like linker does not like some options and they should be omitted for Mac at the configuration stage `make config`.

**Comment by alex-tee** [comment]
`uname -m` says `arm64`

**Comment by alex-tee** [comment]
Also the library suffix doesn't seem to be detected properly for mac. It says it's trying to build an `.so` library but it should be `.dylib` (if building a shared library which is the default)

**Comment by sadko4u** [comment]
And what do the `uname -s` and `uname -o` say?

**Comment by sadko4u** [comment]
OK, I'll add some patches to the build system a bit later.

**Comment by alex-tee** [comment]
Thanks!

**Comment by sadko4u** [comment]
I did some changes. Please try them.
https://github.com/lsp-plugins/lsp-dsp-lib/commit/3132772c1d714130bd9a06db6a16aaedfc2cfffe

**Comment by alex-tee** [comment]
I'm getting some weird error after making those changes to the released tarball, some string is empty:

![image](https://github.com/user-attachments/assets/8cf5e539-dff9-482e-94b1-7d99e2b866de)

When trying from the devel branch directly, I can't fetch the dependencies:

![image](https://github.com/user-attachments/assets/1cdefac9-6c7a-4f40-ace2-d8bfe5c0da77)

Make version info:

![image](https://github.com/user-attachments/assets/d0083c02-417a-47a2-873a-31460c33796b)

(kinda off-topic, but is there a reason for using custom makefiles instead of something like cmake? It seems like it would be much easier to support various platforms by just using a build system generator)

**Comment by sadko4u** [comment]
Oh, LSP Plugins require GNU Make 4.1 and later. It seems that GNU Make 3.81 is one of the problems.
I think, even with CMake there could be problems of compiling for MacOS.

**Comment by alex-tee** [comment]
Ah I see! I installed gmake from homebrew, which is a newer version and now I can proceed to compile the git branch. It seems that the c++ standard is not specified in the compilation flags? Probably missing a --std=c++11 somewhere

![image](https://github.com/user-attachments/assets/a8f5a36c-7ce4-4c52-80dc-17b61bcf0b55)

**Comment by alex-tee** [comment]
In `lsp-common-lib/include/lsp-plug.in/stdlib/locale.h`, it needs a:

```c++
#ifdef __APPLE__
#include "xlocale.h"
#endif
#include "locale.h"
...
```

and also the change below

![image](https://github.com/user-attachments/assets/1f78ae82-fa4f-4a8a-9fea-b37d7b5311b2)

and then it fails at linking:

![image](https://github.com/user-attachments/assets/98b1fc7a-8d4a-464f-b050-19e1ce2fef91)

**Comment by sadko4u** [comment]
> It seems that the c++ standard is not specified in the compilation flags?

We assume that modern gcc automatically sets up standard to at least C++11, so actually we don't need to specify it. We used to explicitly define `--std=c++98` previously.

About patches: I'll apply them soon.

About linkage error: please launch  `make VERBOSE=1` to see the command line.

**Comment by alex-tee** [comment]
> GCC and Clang automatically set up standard to at least C++11

I see, well Apple's clang doesn't seem to do that (on my machine at least). Doesn't hurt to add it explicitly I think.

Here's the full linker command (at the end). I show the compilation commands too in case they show something useful):

![image](https://github.com/user-attachments/assets/1bcdba44-b910-4433-8fa3-42f576c6f7e8)

**Comment by sadko4u** [comment]
It may be the problem that `*.o` files are now compiled for the wrong target architecture.

**Comment by sadko4u** [comment]
I've pushed several changes to `devel` branches, try to re-fetch changes and build withiout specifying `CXXFLAGS` option.

Also, that is very sad that `features.h` should be modified in such way. That means that we have no proper way to detect support of ARM ASIMD/NEON for the CPU.

**Comment by alex-tee** [comment]
It builds without `CXXFLAGS` now, but still fails at linking with the same error.

The .o file seems to be the correct architecture:

![image](https://github.com/user-attachments/assets/c2f1ceaa-4a96-46ad-b7ff-4676d1207b8f)

From what I read online, Apple has its own specific way to detect ARM at runtime. See this for info:
https://github.com/jfalcou/eve/issues/1478

And the implementation: https://github.com/jfalcou/eve/commit/b89df5d347e88857504014781b6a2e85d792ed60

**Comment by sadko4u** [comment]
It looks like several `*.o` files have invalid/incompatible format. Maybe `ld -r` produces incompatible `*.o` file and needs some tuning.
Is it possible for you to determine the format of `lsp-dsp-lib.o` and any other regular `*.o` file produced by `clang`?

**Comment by sadko4u** [comment]
Got `lsp-dsp-lib` built on MacBook M1:
```
Overall unit test statistics:
  execution time [s]:   0.49
  launched:             135
  ignored:              0
  succeeded:            135
  failed:               0

macbook-m1:lsp-dsp-lib sadko$
```

The main problem with linker was, the linker for MacOS was required to pass the `-keep_private_externs` option to not to loss symbols marked as `-fvisibility=hidden`.

**Comment by sadko4u** [comment]
Fixed in 1.0.28 release.
